services:
  postgres-b:
    image: postgres:17-alpine3.23
    container_name: postgres-b
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init-target.sql
